# https://github.com/techtter/scrum-board/blob/master/docker-compose.yml
version: '3.9'

services:
  db:
    image: 'postgres:13.3-alpine'
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    restart: always

  server:
    build: ./apps/server
    container_name: server
    environment:
      - DB_SERVER=postgres
      - DB_PORT=5432
      - POSTGRES_DB=app_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '8080:8080'
    depends_on:
      - db

  client:
    build: ./apps/client
    container_name: client
    ports:
      - '4200:80'
    depends_on:
      - server

volumes:
  postgres: {}
